services:
  web1:
    image: nginx:alpine3.18-slim
    container_name: hola1
    restart: unless-stopped
    tty: true
    volumes:
      - ./web1/nginx/conf.d/:/etc/nginx/conf.d
      - ./web1/www:/var/www
    networks:
      proxyweb:
        ipv4_address: 172.27.10.11
    expose:
      - "80"

  web2:
    image: nginx:alpine3.18-slim
    container_name: hola2
    restart: unless-stopped
    tty: true
    volumes:
      - ./web2/nginx/conf.d/:/etc/nginx/conf.d
      - ./web2/www:/var/www
    networks:
      proxyweb:
        ipv4_address: 172.27.10.12
    expose:
      - "80"

  proxy:
    image: nginx:alpine3.18-slim
    container_name: holaproxy
    restart: unless-stopped
    tty: true
    volumes:
      - ./proxy/nginx/conf.d/:/etc/nginx/conf.d      
      - ./proxy/www:/var/www
      - ./proxy/nginx/ssl:/etc/nginx/ssl 
      - ./nextcloud:/var/www/html    
    networks:
      proxyweb:
        ipv4_address: 172.27.10.2
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
    - "tfgraul:host-gateway"

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-web
    restart: unless-stopped
    networks:
      proxyweb:
        ipv4_address: 172.27.10.20
    expose:
      - "80"
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    extra_hosts:
    - "tfgraul:host-gateway"

  collabora:
    image: collabora/code:latest
    container_name: collabora-web
    restart: unless-stopped
    networks:
      proxyweb:
        ipv4_address: 172.27.10.21
    expose:
      - "9980"
    environment:
      - domain=tfgraul
      - DONT_GEN_SSL_CERT=1
      - extra_params=--o:ssl.enable=false
      - username=admin
      - password=admin_password
      - aliasgroup1=tfgraul
    cap_add:
      - MKNOD
    extra_hosts:
      - "tfgraul:host-gateway"

  db:
    image: mariadb
    container_name: mariadb-last
    networks:
      proxyweb:
        ipv4_address: 172.27.10.30
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_data:/var/lib/mysql

volumes:
  nextcloud_data:
  db_data:

networks:
  proxyweb:
    ipam:
      config:
        - subnet: 172.27.10.0/26